from abc import ABC, abstractmethod

from app.domain.entities.document import Document


class DocumentRepository(ABC):
    @abstractmethod
    async def create(
        self, *, document_id: str, subject_id: str, original_filename: str, storage_path: str, file_type: str
    ) -> Document:
        """The id is generated by the caller (DocumentService), not the
        repository, because the file has to be saved to storage — keyed by
        that same id — before the row referencing its storage_path can be
        created; storage.save() needs the id before the row exists."""
        ...

    @abstractmethod
    async def get_by_id(self, document_id: str) -> Document | None: ...

    @abstractmethod
    async def list_by_subject(self, subject_id: str) -> list[Document]: ...

    @abstractmethod
    async def mark_processing(self, document_id: str) -> None: ...

    @abstractmethod
    async def mark_ready(self, document_id: str, *, page_count: int) -> None: ...

    @abstractmethod
    async def mark_failed(self, document_id: str, *, error_message: str) -> None: ...

    @abstractmethod
    async def set_classification(
        self, document_id: str, *, document_type: str, chapter_id: str | None, lesson_id: str | None, confidence: float
    ) -> None: ...

    @abstractmethod
    async def delete(self, document_id: str) -> None: ...
