from abc import ABC, abstractmethod

from app.domain.entities.document import Document


class DocumentRepository(ABC):
    @abstractmethod
    async def create(
        self,
        *,
        document_id: str,
        subject_id: str,
        original_filename: str,
        storage_path: str,
        file_type: str,
        content_hash: str | None = None,
    ) -> Document:
        """The id is generated by the caller (DocumentService), not the
        repository, because the file has to be saved to storage — keyed by
        that same id — before the row referencing its storage_path can be
        created; storage.save() needs the id before the row exists."""
        ...

    @abstractmethod
    async def get_by_id(self, document_id: str) -> Document | None: ...

    @abstractmethod
    async def get_by_subject_and_hash(self, subject_id: str, content_hash: str) -> Document | None:
        """Used for upload-time dedup — a document with this exact byte
        content already exists (in any non-failed status) for this subject."""
        ...

    @abstractmethod
    async def list_by_subject(self, subject_id: str) -> list[Document]: ...

    @abstractmethod
    async def mark_processing(self, document_id: str) -> None: ...

    @abstractmethod
    async def update_progress(self, document_id: str, *, step: str, progress: int) -> None:
        """Optional fine-grained status within "processing" — purely
        informational for the upload-progress UI, doesn't gate anything."""
        ...

    @abstractmethod
    async def mark_ready(self, document_id: str, *, page_count: int) -> None: ...

    @abstractmethod
    async def mark_failed(self, document_id: str, *, error_message: str) -> None: ...

    @abstractmethod
    async def set_classification(
        self, document_id: str, *, document_type: str, chapter_id: str | None, lesson_id: str | None, confidence: float
    ) -> None: ...

    @abstractmethod
    async def delete(self, document_id: str) -> None: ...
